export const constants: Record<string, string> = {
    INITIALIZE_STR: '',
    comOperatorExp: 'comOperatorExp',
    logOperatorExp: 'logOperatorExp',
    conditionMemberExp: 'conditionMemberExp',
    openBracExp: 'openBracExp',
    ArithOperatorExp: 'ArithOperatorExp',
    groupOperatorExp: 'groupOperatorExp',
    closeBracExp: 'closeBracExp',
    queryFuncExp: 'queryFuncExp',
    notExp: 'notExp',
    andExp: 'andExp',
    orExp: 'orExp',
    SINGLE_QUOTE: `'`,
};
